// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omcumxuxukmigemjzfdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tY3VteHV4dWttaWdlbWp6ZmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NTU5MzIsImV4cCI6MjA2NjMzMTkzMn0.6hXN_kRH4MYrhcNUI3-JhO7MP6AV1IaWc7Mj_piW3G4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);